### ISSUE TITLE
License request and project rename

### ISSUE THREAD

**Issue by mikefedyk** [dizzythinks/asg_persistence#1]
Hi,

At a previous job I extensively modified this script in-house to work with multiple volumes and tag matching on instance and volume tags to give persistent hostnames.  Also another feature that uses a similar mechanism (but that I never implemented in-house) would allow for persistent hostnames without using volumes.

I want to reimplement these features based on this project in the open, but want two things done here first:

The first is applying a license to the code.  I recommend the Apache 2 license for corp friendlyness.

The second is to rename the project.  Before the persistent hostname feature without volumes, I would have asked for a name like attach_volume, but since that feature doesn't require a volume at all, I am requesting the name asg_persistent, or maybe something similar.

Mike

**Comment by mikefedyk** [comment]
I realize this was posted on April 1st, but this is a serious request.

**Comment by dizzythinks** [comment]
Happy to do this although I have renamed it "asg_persistence". Someone I know called Jerry mentioned this was being used, am wondering if that person he mentioned was yourself?

**Comment by mikefedyk** [comment]
Yes, that was me.

**Comment by mikefedyk** [comment]
And thanks! :)

**Comment by dizzythinks** [comment]
Hah! Glad it was useful. Look forward to seeing changes.

**Comment by dizzythinks** [comment]
Happy to add you as a collaborator on the repo.

**Comment by mikefedyk** [comment]
Cool, I'll likely start with the options code to give the structure of the remaining work.  I'll make another issue for that and bring up the details so we can agree on which direction to go.
